[connections.gsheets]
# This first one is just to satisfy the connection setup
spreadsheet = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1666424592#gid=1666424592"

# Your 4 specific tab links (Replace with your actual links from the browser)
url_avail = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1666424592#gid=1666424592"
url_2g = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1889682012#gid=1889682012"
url_3g = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1051252556#gid=1051252556"
url_4g = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1624902543#gid=1624902543"
url_site = "https://docs.google.com/spreadsheets/d/1M5r0AhG_W8bDa2272GL6gcWMl_7cYZuEy8xwE1SzaT4/edit?gid=1597149608#gid=1597149608"
